const ERROR_CODE = Object.freeze({
    VALIDATION_FAILED: "VALIDATION_FAILED",
    UNAUTHORIZED: "UNAUTHORIZED",
    AUTH_SESSION_INVALID: "AUTH_SESSION_INVALID",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
    RATE_LIMITED: "RATE_LIMITED",
    UPLOAD_INVALID: "UPLOAD_INVALID",
    UPLOAD_TOO_LARGE: "UPLOAD_TOO_LARGE",
    DATABASE_CONFLICT: "DATABASE_CONFLICT",
    DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
    DATABASE_ERROR: "DATABASE_ERROR",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    PAYMENT_PROVIDER_ERROR: "PAYMENT_PROVIDER_ERROR",
    INTERNAL_ERROR: "INTERNAL_ERROR",
});

const STATUS_ERROR_CODE = Object.freeze({
    400: ERROR_CODE.VALIDATION_FAILED,
    401: ERROR_CODE.UNAUTHORIZED,
    402: ERROR_CODE.PAYMENT_REQUIRED,
    403: ERROR_CODE.FORBIDDEN,
    404: ERROR_CODE.NOT_FOUND,
    409: ERROR_CODE.CONFLICT,
    413: ERROR_CODE.UPLOAD_TOO_LARGE,
    429: ERROR_CODE.RATE_LIMITED,
    500: ERROR_CODE.INTERNAL_ERROR,
    502: ERROR_CODE.PAYMENT_PROVIDER_ERROR,
    503: ERROR_CODE.DATABASE_UNAVAILABLE,
});

const errorCodeForStatus = (statusCode) => (
    STATUS_ERROR_CODE[statusCode] || ERROR_CODE.INTERNAL_ERROR
);

module.exports = { ERROR_CODE, errorCodeForStatus };
